# Generated by Django 3.2.10 on 2022-03-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='listing_of_accommodationthat_seller_offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_offering_accommodation', models.CharField(max_length=256)),
                ('model_property', models.CharField(max_length=256)),
                ('model_Property_Address', models.CharField(max_length=256)),
                ('model_property_bedrooms', models.CharField(max_length=256)),
                ('model_property_bathrooms', models.CharField(max_length=256)),
                ('model_Parking', models.CharField(max_length=256)),
                ('model_Internet', models.CharField(max_length=256)),
                ('model_Total_number_of_flatmates', models.CharField(max_length=256)),
                ('model_Room_name', models.CharField(max_length=256)),
                ('model_Room_type', models.CharField(max_length=256)),
                ('model_Room_furnishings', models.CharField(max_length=256)),
                ('model_Bathroom_type', models.CharField(max_length=256)),
                ('model_Bed_Size', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Bed_side_table', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Wardrobe', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Drawers', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Air_conditioner', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Heater', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Desk', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Lamp', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Chair', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Couch', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_TV', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Balcony', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Door_lock', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Room_furnishings_features_Kitchenette', models.CharField(blank=True, max_length=256, null=True)),
                ('model_room_Weekly_rent', models.IntegerField()),
                ('model_room_changed_Bond', models.CharField(max_length=256)),
                ('model_room_changed_Bills', models.CharField(max_length=256)),
                ('model_Room_availability_Date', models.DateField(max_length=256)),
                ('model_Room_availability_Minimum_length_stay', models.CharField(max_length=256)),
                ('model_Room_availability_Maximum_length_stay', models.CharField(max_length=256)),
                ('model_Property_and_room_images_1', models.ImageField(blank=True, null=True, upload_to='')),
                ('model_Property_and_room_images_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('model_Property_and_room_images_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('model_Property_and_room_images_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('model_Property_and_room_images_5', models.ImageField(blank=True, null=True, upload_to='')),
                ('model_Flatmate_Preference_name', models.CharField(max_length=256)),
                ('model_Accepting_Backpackers', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Accepting_Students', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Accepting_Smokers', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Accepting_LGBTI', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Accepting_years_olds', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Accepting_Children', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Accepting_Pets', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Accepting_Retirees', models.CharField(blank=True, max_length=256, null=True)),
                ('model_Accepting_On_welfare', models.CharField(blank=True, max_length=256, null=True)),
                ('model_introduce_about_your_flatmates', models.TextField()),
                ('model_introduce_great_about_living', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'listing of accommodationthat seller offering',
            },
        ),
    ]
