# Generated by Django 3.2.10 on 2022-03-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='model_property',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
