# Generated by Django 3.2.10 on 2022-03-06 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0004_auto_20220306_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='accommodationthat_seller_offering_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_Property_and_room_images_1', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('model_Property_and_room_images_2', models.ImageField(blank=True, null=True, upload_to='')),
                ('model_Property_and_room_images_3', models.ImageField(blank=True, null=True, upload_to='')),
                ('model_Property_and_room_images_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('model_Property_and_room_images_5', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name_plural': 'listing of accommodationthat seller offering images',
            },
        ),
        migrations.RemoveField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='model_Property_and_room_images_2',
        ),
        migrations.RemoveField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='model_Property_and_room_images_3',
        ),
        migrations.RemoveField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='model_Property_and_room_images_4',
        ),
        migrations.RemoveField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='model_Property_and_room_images_5',
        ),
    ]
