# Generated by Django 3.2.10 on 2022-03-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0005_auto_20220306_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='model_Property_and_room_images_1',
        ),
        migrations.AddField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='model_Property_and_room_images_1',
            field=models.ManyToManyField(blank=True, null=True, to='app_one.accommodationthat_seller_offering_image'),
        ),
    ]
