# Generated by Django 3.2.10 on 2022-03-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0007_auto_20220306_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodationthat_seller_offering_image',
            name='model_Property_and_room_images_2',
        ),
        migrations.RemoveField(
            model_name='accommodationthat_seller_offering_image',
            name='model_Property_and_room_images_3',
        ),
        migrations.RemoveField(
            model_name='accommodationthat_seller_offering_image',
            name='model_Property_and_room_images_4',
        ),
        migrations.RemoveField(
            model_name='accommodationthat_seller_offering_image',
            name='model_Property_and_room_images_5',
        ),
    ]
