# Generated by Django 3.2.9 on 2022-03-14 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_one', '0008_auto_20220306_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='link_with_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
