# Generated by Django 3.2.9 on 2022-03-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0009_listing_of_accommodationthat_seller_offering_link_with_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_info_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(blank=True, max_length=256, null=True)),
                ('User_photo', models.ImageField(blank=True, null=True, upload_to='image/user_pic/')),
                ('User_Number', models.CharField(blank=True, max_length=256, null=True)),
                ('User_Email', models.CharField(blank=True, max_length=256, null=True)),
                ('User_Password', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'User Information Table',
            },
        ),
    ]
