# Generated by Django 3.2.9 on 2022-03-25 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0010_user_info_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_info_table',
            name='Joined_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 25, 11, 16, 12, 338634)),
        ),
    ]
