# Generated by Django 3.2.9 on 2022-03-25 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0012_auto_20220325_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='List_create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 25, 19, 14, 19, 904232), null=True),
        ),
        migrations.AlterField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='model_introduce_about_your_flatmates',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='model_introduce_great_about_living',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_info_table',
            name='Joined_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 25, 19, 14, 19, 901241)),
        ),
    ]
