# Generated by Django 3.2.9 on 2022-03-25 14:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0014_auto_20220325_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='List_create_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 25, 20, 57, 7, 592617), null=True),
        ),
        migrations.AlterField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='List_create_date',
            field=models.DateTimeField(blank=True, default=datetime.date(2022, 3, 25), null=True),
        ),
        migrations.AlterField(
            model_name='user_info_table',
            name='Joined_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 25, 20, 57, 7, 590623)),
        ),
    ]
