# Generated by Django 3.2.9 on 2022-03-25 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0015_auto_20220325_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='List_create_date',
        ),
        migrations.AlterField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='List_create_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 25, 20, 58, 11, 544436), null=True),
        ),
        migrations.AlterField(
            model_name='user_info_table',
            name='Joined_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 25, 20, 58, 11, 541445)),
        ),
    ]
