# Generated by Django 3.2.9 on 2022-03-25 16:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0019_auto_20220325_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing_of_accommodationthat_seller_offering',
            name='List_create_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 25, 22, 43, 8, 834600), null=True),
        ),
        migrations.AlterField(
            model_name='user_info_table',
            name='Joined_Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 25, 22, 43, 8, 830610)),
        ),
    ]
